{
  "stats": {
    "suites": 1,
    "tests": 3,
    "passes": 0,
    "pending": 0,
    "failures": 3,
    "start": "2024-01-18T19:54:21.063Z",
    "end": "2024-01-18T19:54:30.846Z",
    "duration": 9729,
    "testsRegistered": 3,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "57d03a80-5bd7-4a9b-b5d5-c9566e92cada",
      "title": "",
      "fullFile": "cypress/integration/promiseBasic.spec.js",
      "file": "cypress/integration/promiseBasic.spec.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [],
      "suites": [
        {
          "uuid": "3792d19d-8b68-4cfb-af74-3b30d8de1498",
          "title": "Promise basic app",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "should resolve first promise by click on logo",
              "fullTitle": "Promise basic app should resolve first promise by click on logo",
              "timedOut": null,
              "duration": 3299,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.get('.logo').click({\n  force: true\n});\ncy.get('.message').contains('Promise was resolved!');",
              "err": {
                "message": "ReferenceError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > error is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "ReferenceError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > error is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at http://localhost:8080/index.f75de5e1.js:22:26",
                "diff": null
              },
              "uuid": "aa5f006c-17fc-4d1d-88b2-e94a94b3b448",
              "parentUUID": "3792d19d-8b68-4cfb-af74-3b30d8de1498",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "should reject second promise in 3 seconds",
              "fullTitle": "Promise basic app should reject second promise in 3 seconds",
              "timedOut": null,
              "duration": 3203,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.get('.error-message', {\n  timeout: 3000\n}).contains('Promise was rejected!');",
              "err": {
                "message": "AssertionError: Timed out retrying after 3000ms: Expected to find element: `.error-message`, but never found it.",
                "estack": "AssertionError: Timed out retrying after 3000ms: Expected to find element: `.error-message`, but never found it.\n    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress\\integration\\promiseBasic.spec.js:110:8)",
                "diff": null
              },
              "uuid": "6275f145-038a-45fc-8b6d-a04c6e89d85d",
              "parentUUID": "3792d19d-8b68-4cfb-af74-3b30d8de1498",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "shouldn't resolve any promise by right click",
              "fullTitle": "Promise basic app shouldn't resolve any promise by right click",
              "timedOut": null,
              "duration": 3227,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.get('.logo').rightclick({\n  force: true\n});\ncy.get('.message').should('not.visible');",
              "err": {
                "message": "ReferenceError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > error is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "ReferenceError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > error is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at http://localhost:8080/index.f75de5e1.js:22:26",
                "diff": null
              },
              "uuid": "b0009e93-11ed-4732-a96d-1fcc52170286",
              "parentUUID": "3792d19d-8b68-4cfb-af74-3b30d8de1498",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "aa5f006c-17fc-4d1d-88b2-e94a94b3b448",
            "6275f145-038a-45fc-8b6d-a04c6e89d85d",
            "b0009e93-11ed-4732-a96d-1fcc52170286"
          ],
          "pending": [],
          "skipped": [],
          "duration": 9729,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        }
      ],
      "passes": [],
      "failures": [],
      "pending": [],
      "skipped": [],
      "duration": 0,
      "root": true,
      "rootEmpty": true,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "reportDir": "raw_reports",
        "overwrite": false,
        "html": false,
        "json": true
      },
      "version": "6.2.0"
    }
  }
}